### PR TITLE
Add slack webhook

### PR DESCRIPTION
**Pull request by scriptsrc**
We'll need to set a new envvar with the URL of our Slack webhook.

### CODE REVIEW

**Comment by sarahc23** [comment]
Sorry I know you've done a lot of work on this, but do you think this would make more sense as a part of super-linter? Since I see super-linter as something that issues out summaries and gives red Xes/green checkmarks, which is a very similar function to Slack notifications here.

**Comment by sarahc23** [comment]
Oh sorry I see individual violations being posted to Slack here which... I'm not sure I agree with? I think individual line-by-line comments for each of the violations is most useful and helpful in the PR itself. I'm not sure how seeing a text dump of all the issues (and with no surrounding code context, at that, to be able to make sense of it in a Slack message) is all that actionable.

However, a single Slack message saying 'you have some linting issues in X PR in these files' *does* seem handy and useful.

**Comment by scriptsrc** [comment]
TO FIX: 

- [x] A check `if self._all_violations.items():` should be added so we don't send a slack message with zero violations.
- [x] Remove py2.7 and 3.5 from unittests so we can use f-strings.

**Comment by scriptsrc** [comment]
I don't understand why you would prefer to have this in super-linter over lintly.

Lintly is responsible for parsing the output of all the different tools and communicating those issues back to the humans.

If we were to move this to super-linter, we would need to build a way for super-linter to parse the output of all of these tools. That is similar to what the `tap` support was in super-linter, but they removed that and when it was present in super-linter it seemed to have less information than what Lintly has.

> I see individual violations being posted to Slack

It posts once per invocation of Lintly. That post contains a summary of all the violations found. It provides a button in the bottom of the notification to "View PR". The way we are using super-linter, this means up to one message per tool per PR. We can iterate on this going forward but the objective is for us to be able to monitor all the issues found by Superlinter across all the repositories that have been onboarded without us having to browse through all the recent PRs on all the projects we have onboarded.

So It's not a text dump - It's a summary of issues found. 
- Security Tool
- File name
- line number
- Message from the security tool
- Button to go view the PR.

I did attempt to include the `Violation.code` information but that didn't seem to provide important context.

**Comment by nandusekarv10** [comment]
I feel this is really good idea to have all the findings in one place. As now we have to go to each project and look for each PR to check if it run properly or not. 

But as Sarah said if we have each individual  violations to be posted in slack, over the time may be we will get overwhelmed. But we can start now and will see if we can modify anything in that.

@scriptsrc But there is another use case where `Superlinter` were found issues but `Lintly` was not invoke. So just to verify that we still need to go and each PR for each project.

**Comment by sarahc23** [comment]
> I don't understand why you would prefer to have this in super-linter over lintly.
> 
> Lintly is responsible for parsing the output of all the different tools and communicating those issues back to the humans.
> 
> If we were to move this to super-linter, we would need to build a way for super-linter to parse the output of all of these tools. That is similar to what the `tap` support was in super-linter, but they removed that and when it was present in super-linter it seemed to have less information than what Lintly has.

So I had no idea you were gonna add this sort of functionality so I'm glad we're doing sprint planning!

I guess what I'm disagreeing on is how much detail is being posted on each PR. In my ideal world, the Slack equivalent of this is the perfect amount of detail -- and this is the type of summary super-linter posts (so I figure we could also piggy-back off of this one):

image

> 
> > I see individual violations being posted to Slack
> 
> It posts once per invocation of Lintly. That post contains a summary of all the violations found. It provides a button in the bottom of the notification to "View PR". The way we are using super-linter, this means up to one message per tool per PR. We can iterate on this going forward but the objective is for us to be able to monitor all the issues found by Superlinter across all the repositories that have been onboarded without us having to browse through all the recent PRs on all the projects we have onboarded.
> 
> So It's not a text dump - It's a summary of issues found.
> 
> * Security Tool
> * File name
> * line number
> * Message from the security tool
> * Button to go view the PR.
> 
> I did attempt to include the `Violation.code` information but that didn't seem to provide important context.

Yeah, I think the line number and message might be too much, especially since we have no context as to what the messages may refer to. What's your use case for *needing* to have the messages in there?

(As for `Violations.code`, it's only something like `B104` for the error message code, so it's not like it's adding something super verbose or anything.)

Maybe it's a personal philosophy thing but I think alerts and messages should contain the important and summary info and ONLY the important info. I don't think you should put as much info there as you can. That's what logs are for.

Personally I think the right amount of detail would be something like this:

```
<checkmark> Bandit
- No issues found
<angry red x> Flake8
- 3 issues found in some_file.py
- 2 issues found in another_file.py
...
<view PR button>
```
And this looks pretty similar to the checks pane above!

**Pull request merged**
